### ISSUE TITLE
Add ability to check for new release candidates and ping `@Playtester` accordingly

### ISSUE THREAD

**Issue by GeckoEidechse** [itscynxx/Spectre#33]
This feature request is basically to make my own life as a release manager for Northstar easier :>

## Problem

When I make a release candidate for Northstar, I need to

1. Push tags that trigger the release candidate build
2. Message `@Playtester` on Discord with
    1. the version of the release candidate
    2. the current release notes
    3. a link to the release notes
    4. a link to file download (although I stopped that part in favour of only recommending FlightCore)
3. Create a thread for reporting issues with release candidate
4. Link thread in original message

## Solution

Now with the exception of the first step, all other steps could be automated to some degree using Spectre.

So the idea would be that all I need to do is push a new tag on the release repo. Then Spectre just polls the repo every X minutes (let's say like every 20 minutes) or even just abuse the fact that the `#northstar-git` channel will receive a message and use that as a trigger (plus some delay for letting build finish + polling until done)

Once it detects a new release candidate i.e. new tag and tag is formatted as `vA.B.C-rcX` (where `A`, `B`, `C`, and `X` are integers) it then does the remaining steps by generating the release notes and the message to ping playtesters with, then posts it in the `#playtesters-ping` channel, then creates the thread and finally links the thread).

This would greatly reduce the time I spend on creating release candidates as all I would have to do is push the tags for the new release candidate and Spectre would take care of the rest ^^

**Comment by GeckoEidechse** [comment]
I can happily take care of all the parts that interact with GitHub as I dealt with their API before to adding a feature for release note generation to FlightCore.

However I'm not familiar with the structure of Spectre so if someone could lay the ground work with stubbed dummy function for things regarding interacting with Discord that I then build on top off, that would be greatly be appreciated. From there I can take care of the rest :D

**Comment by itscynxx** [comment]
I have a file with the outlines of the actual ping and stuff, the only issue is I think the only way to use github api is to use the graphql api which requires a token from github which i couldn't get working for the life of me

can't use the normal one because it doesn't track discussions, and those are what has the changelogs

**Comment by itscynxx** [comment]
inputting `[R2Northstar/NorthstarLauncher] New tag created: v1.18.1-rc1` in a channel created to replicate #northstar-git results in the following message, where you can specificy the role and channel to send it to.
![image](https://github.com/CooldudePUGS/Spectre/assets/70904206/03f7dc84-008e-4fa1-b24b-6ed4057ddf21)

please give feedback, such as:
should we keep contributors? further, if we do, should we parse for their github links to send in chat?
should we use codeblocks like they are now, or keep the text normal and bold in certain spots?
should we remove the links to the specific prs that the version tests?

the only real issue i had is im 
1. not sure how you mention the thread then link it to the same message
2. dont think discord bots can create specific threads of messages, but it does create one 
![image](https://github.com/CooldudePUGS/Spectre/assets/70904206/c58883ec-1d12-4956-9be0-d43291aef9ba)

**Comment by GeckoEidechse** [comment]
That looks awesome :D
Does it grab the content from the draft or somewhere else?

> should we keep contributors? further, if we do, should we parse for their github links to send in chat?

For playtesting it's not necessarily important IMO. Just do whatever requires least changes for now I guess

> should we use codeblocks like they are now, or keep the text normal and bold in certain spots?

Don't have any clear preference. Code block means that the links to the PRs wouldn't be clickable, so probably not. As long as there is some sort of separation between release notes and rest of content, anything should be fine ^^

> should we remove the links to the specific prs that the version tests?

I think keeping them would actually be quite handy ^^

**Comment by itscynxx** [comment]
Ha, i just realized that i don't need to wait for Gecko to close this issue :P
Pull requests #44 #45 and #47 were all dedicated towards creating a playtester ping via Spectre
The ping itself is functional, with an update command in case it needs to be updated manually
